### ISSUE TITLE
Django 2.0 incompatible

### ISSUE THREAD

**Issue by Euphorbium** [blag/django-secure-mail#3]
Django 2 models require `on_delete` parameter to be set for every model foreign key field.  Default action in django 1 was cascade.

**Comment by blag** [comment]
Confirmed, will get to this later this week. Thanks! 😄

**Comment by blag** [comment]
Fixed in beb324a7e8e260ec43e7e66f0429ee495ac28710.

**Comment by blag** [comment]
Sorry for the delay. Uploaded to [PyPI as version 1.1.0](https://pypi.python.org/pypi/django-secure-mail/1.1.0). You should now be able to upgrade to it with `pip`:

```bash
pip install --upgrade django-secure-mail
```
