### ISSUE TITLE
Non ascii characters get mangled.

### ISSUE THREAD

**Issue by Euphorbium** [blag/django-secure-mail#4]
This might be due to my tools, but it seems like after decryption utf8 characters get mangled. Include charset info in the comment.

**Comment by blag** [comment]
Can you give me some example text that triggers it? I'll double check it on my system and add a test for it. Thanks!

**Comment by blag** [comment]
What is `SECURE_MAIL_GNUPG_ENCODING` set to? Does setting it to `utf-8` fix it?

**Comment by blag** [comment]
Closing due to lack of response. I hope you got it to work properly.
